### ISSUE TITLE
Webcam model

### ISSUE THREAD

**Issue by alessandro-montanari** [NVIDIA-Jetson/redtail#29]
What webcam did you use and what fps where you able to achieve with it?
Thanks for opening up this work!

**Comment by Alexey-Kamenev** [comment]
We tried few cameras but the one you see on the videos is Microsoft LifeCam HD-5000 web camera. Other cameras should work too as long as they work with V4L (one easy way to check is to run one of our GStreamer pipelines using GStreamer or `gscam` node).
The camera was running at 30 fps, our TrailNet was running at the same rate while YOLO - at 1 fps. All rates are configurable via node parameters and/or launch files.
While our usage of cheap web camera was intentional, you don't have to do that: our system works just fine with good cameras like ZED.

**Comment by alessandro-montanari** [comment]
Thanks for the info.
Actually I am planning to use a cheap webcam as well because it will be mounted on a drone and it is more cost effective in case of crash :)

**Comment by Alexey-Kamenev** [comment]
Closing the issue, feel free to re-open or create a new one.
