### ISSUE TITLE
Camera calibration file

### ISSUE THREAD

**Issue by isakdiaz** [NVIDIA-Jetson/redtail#52]
To run the gscam node I am using a camera calibration file created from redtail/tools/camera_rig/widecam_mono_calibration/, yet I am getting a "Failed to parse camera calibration from file" error. It comes from "yaml-cpp: error at line 0, column 0: bad conversion".
Any suggestions? Was the calibration file supposed to be created by other means?

**Comment by Alexey-Kamenev** [comment]
Most likely this happens because OpenCV `FileStorage` writes YAML file that is not compatible with most other YAML readers (e.g. Python etc). The problem is in the first line of the output file, that's why, for example, in our Python script we have to [remove it](../blob/master/tools/camera_rig/scripts/frameSplitter.py#L45).
However, there is a bigger issue: the calibration parameters are not actually used to undistort an image. The reason is `gscam` uses [camera_info_manager](https://github.com/ros-perception/image_common/tree/hydro-devel/camera_info_manager) from `image_common` which reads the calibration file and publishes it as a topic but does not actually perform undistortion. On the other hand, performing undistortion in our code (i.e. `caffe_ros`) node is too late as the node is subscribed to the output of `gscam` which means the image went through GStreamer pipeline like resizing etc so undistorting it does not make sense anymore/too late.
In our case, this was not a problem as our Iris drone used Microsoft HD5000 camera with 66 degrees of diagonal FOV so there was never any noticeable distortions.

For wide angle cameras we would certainly recommend undistorting the image before feeding into `caffe_ros`. In another scenario where we use ZED camera, the ZED ROS node conveniently provides a topic with rectified image ([example](../blob/master/ros/packages/redtail_debug/launch/trailnet_debug_zed.launch)). 

Hope this clarifies things a little...
