### ISSUE TITLE
TBS Discovery J120 Power

### ISSUE THREAD

**Issue by isakdiaz** [NVIDIA-Jetson/redtail#53]
The TBS Discovery build shows the J120 hooked up directly to the power coming from the battery. I thought the power fluctuations coming from the battery had the potential to damage the equipment. Have you guys had any issues with this?

**Comment by Alexey-Kamenev** [comment]
While we have not had any issues with such connection, it may indeed cause some problems.  First of all, as long as you are using LiPo batteries 2S-4S you should be fine - J120 power voltage range is 7-17V. Using anything above 4S will damage the board. We tried 2S, 3S and 4S batteries on different platforms that used J120 (drones and rovers) and they all worked fine.

However, even when a proper battery is used, there still might be problems due to voltage spikes/drops. As long as you are monitoring the battery level and avoid flying when the battery level is low then most likely you should not experience any problems. In case Jetson is unexpectedly powered down midflight, PX4 safety mechanism will kick in and the vehicle will switch from Offboard mode to the last mode (e.g. Position Hold). PX4 in Offboard mode requires companion computer to publish updates at the minimum rate of 2Hz.

Now, the reason we had to make such connection is TBS Core power module that we planned to use originally to power Jetson, does not provide enough power for the Jetson: its 12V output is only 600mA, while Jetson requires at least 1A to power on reliably at that voltage.
Ideally, there should be a completely separate battery (e.g. small 2S battery) to power Jetson alone, but TBS Disco platform is too small for that.

**Comment by maciejmatuszak** [comment]
Just sharing my experience.
I had similar setup J120 + TX1 connected directly to 4S battery. We use 4in1 ESC that have very minimal filtering capacitors. As a results there were ~5V spikes when motor started/stoped. My J120 did not survived that :( it released the blue smoke... along with ZED camera, the TX1 survived somehow...
That was expensive smoke... Upon contacting Auvidea they advised to setup 12V DC/DC converter in between battery and the carrier board. Fully charged 4S is 16.4V which is very close to the J120 limits.

**Comment by isakdiaz** [comment]
That sucks, the J120 board costs almost as much as the TX2! If you don't mind a little extra weight then using transmitter lipos is the best solution I've found. It has undervoltage protection (9V) and overcurrent protection (3A). I use these for my LIDAR aswell.

https://hobbyking.com/en_us/turnigy-9xr-safety-protected-11-1v-3s-2200mah-1-5c-transmitter-pack.html

**Comment by maciejmatuszak** [comment]
ZED camera cost about the same :) blue smoke is expensive. 
After this disaster I had extra battery but it was bothersome. I am using the DC/DC converter for 1.5 year now and all is ok.

**Comment by Alexey-Kamenev** [comment]
Sorry to hear that. As I mentioned, ideal solution would be a separate battery but if it's not possible then appropriate [voltage regulator](https://hobbyking.com/en_us/radios-servos/sbec-ubec-regulator/voltage-regulator.html) should help.
