### ISSUE TITLE
Hardware Question - PWM Board

### ISSUE THREAD

**Issue by CapitalZe** [NVIDIA-Jetson/redtail#79]
Hello,

I've acquired almost all the hardware required and initiated the physical build.
I am struggling, however, to identify the exact 8-Channel PWM board used in the wiki section.

If anyone has the name/brand/model no or could provide the name of a supplier I'd be very grateful.

Cheers!

**Comment by Alexey-Kamenev** [comment]
We used the same receiver, [D4R-II](https://www.getfpv.com/frsky-d4r-ii-4ch-2-4ghz-accst-receiver-w-telemetry.html), that comes with 3DR Iris+ on our TBS build just because we have a bunch of Irises some of which we use for parts.
In my personal builds I prefer using [X8R](https://www.getfpv.com/frsky-x8r-16ch-receiver-sbus-smart-port-amplified-pcb-antenna.html) with Taranis X9D+ transmitter ([combo](https://www.getfpv.com/frsky-x8r-16ch-receiver-sbus-smart-port-amplified-pcb-antenna.html)) but it's totally up to you.

**Comment by Alexey-Kamenev** [comment]
Closing, feel free to re-open or create a new one.

**Comment by CapitalZe** [comment]
Thanks!

**Comment by CapitalZe** [comment]
Ah, reviewing your answer I believe you may have misunderstood; or, which is more likely, I formatted the question incorrectly.

What I am looking for is the PWM, as in the first image, and PBD, as in the second image.
I have everything else at hand and these are the final components I am struggling to source.

Would you be able to share make and model numbers, if you have them, and possibly suppliers you used?

Many thanks!

<img width="502" alt="screen shot 2018-08-29 at 15 49 57" src="https://user-images.githubusercontent.com/35135320/44792061-5b06ee80-aba3-11e8-9e45-903d2c569641.png">

<img width="475" alt="screen shot 2018-08-29 at 15 49 51" src="https://user-images.githubusercontent.com/35135320/44792038-52161d00-aba3-11e8-8e20-1223fb89dd97.png">
